### ISSUE TITLE
Incorrect install command

### ISSUE THREAD

**Issue by dnebauer** [astroidmail/astroid-syntax-highlight#2]
The plugin name in the install instructions is incorrect: should be `astroid-syntax-highlight` but is given as `syntax-highlight`.

**Comment by gauteh** [comment]
dnebauer writes on September 9, 2018 21:02:
> The plugin name in the install instructions is incorrect: should be `astroid-syntax-highlight` but is given as `syntax-highlight`.

thanks, fixed.
